from setuptools import setup, find_packages

setup(
    name="vulnforge",
    version="1.0.0",
    packages=find_packages(),
    py_modules=[
        # Top-level modules used by the CLI that are not in a package directory
        "vulnforge_main",
        "recon_module",
        "ai_integration",
        "ai_orchestrator",
        "ai_controller",
    ],
    install_requires=[
        "requests",
        "aiohttp",
        "aiofiles",
        "beautifulsoup4",
        "python-nmap",
        "dnspython",
        "colorama",
        "rich",
        "jinja2",
        "markdown",
        "click",
        "yaspin",
        "PySocks",
        "streamlit",
        "langchain-core",
        "langchain-openai",
        "langchain-ollama",
        "langchain-anthropic",
        "langchain-google-genai",
        "langchain-community",
        "openai",
        "anthropic",
        "google-generativeai",
    ],
    entry_points={
        "console_scripts": [
            "vulnforge=vulnforge_main:main",
        ],
    },
    author="DemonKing369.0",
    author_email="arunking9@gmail.com",
    description="AI-Powered Security Framework for Bug Bounty Warriors",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Arunking9/VulnForge",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Security",
    ],
    python_requires=">=3.8",
)
