from setuptools import setup, find_packages

setup(
    name="neurorift",
    version="1.0.0",
    packages=find_packages(
        include=[
            "modules",
            "modules.*",
            "utils",
            "utils.*",
            "ai_wrapper",
            "ai_wrapper.*",
        ]
    ),
    py_modules=[
        # Top-level modules used by the CLI
        "neurorift_main",
        "recon_module",
        "ai_integration",
        "ai_orchestrator",
        "ai_controller",
    ],
    package_data={
        "modules": ["**/*.json", "**/*.md"],
        "prompts": ["**/*.md", "**/*.txt"],
        "configs": ["*.json"],
    },
    include_package_data=True,
    install_requires=[
        "requests>=2.31.0",
        "aiohttp>=3.9.0",
        "aiofiles>=23.2.0",
        "beautifulsoup4>=4.12.0",
        "python-nmap>=0.7.1",
        "dnspython>=2.4.0",
        "colorama>=0.4.6",
        "rich>=13.7.0",
        "jinja2>=3.1.0",
        "markdown>=3.5.0",
        "click>=8.1.0",
        "yaspin>=3.0.0",
        "PySocks>=1.7.1",
        "streamlit>=1.29.0",
        "python-dotenv>=1.0.0",
        "langchain-core>=0.1.0",
        "langchain-openai>=0.0.5",
        "langchain-ollama>=0.0.1",
        "langchain-anthropic>=0.1.0",
        "langchain-google-genai>=0.0.6",
        "langchain-community>=0.0.20",
        "openai>=1.10.0",
        "anthropic>=0.8.0",
        "google-generativeai>=0.3.0",
    ],
    entry_points={
        "console_scripts": [
            "neurorift=neurorift_main:main",
        ],
    },
    author="demonking369",
    author_email="",
    description="Terminal-Based Multi-Agent Intelligence System for Security Research",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/demonking369/NeuroRift",
    project_urls={
        "Bug Tracker": "https://github.com/demonking369/NeuroRift/issues",
        "Documentation": "https://github.com/demonking369/NeuroRift",
        "Source Code": "https://github.com/demonking369/NeuroRift",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Information Technology",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Security",
        "Topic :: System :: Networking",
        "Operating System :: POSIX :: Linux",
    ],
    python_requires=">=3.10",
    keywords="security penetration-testing bug-bounty ai multi-agent reconnaissance vulnerability-scanning",
)
