import type { PanelDefinition, PanelId, PanelSlot } from '@/lib/webmode/types';

export const panelDefinitions: PanelDefinition[] = [
    {
        id: 'command',
        title: 'Command Fabric',
        description: 'Chat-first control surface with intent routing.',
        slot: 'primary',
        category: 'AI_CONTROL',
        policy: { requiresSession: true },
        tone: 'signal',
    },
    {
        id: 'activity',
        title: 'Activity Stream',
        description: 'Event-bus view of agent negotiation & critique.',
        slot: 'secondary',
        category: 'SYSTEM',
        policy: { requiresSession: true },
    },
    {
        id: 'agent-graph',
        title: 'Agent State Graph',
        description: 'Live topology of agent roles, states, and trust weights.',
        slot: 'primary',
        category: 'AI_CONTROL',
        policy: { requiresSession: true, minTier: 'tablet' },
    },
    {
        id: 'intent-flow',
        title: 'Intent → Action Flow',
        description: 'Policy-driven intent routing and gating map.',
        slot: 'primary',
        category: 'AI_CONTROL',
        policy: { requiresSession: true },
    },
    {
        id: 'execution-timeline',
        title: 'Execution Pipeline',
        description: 'Deterministic execution path with enforcement checkpoints.',
        slot: 'secondary',
        category: 'OPERATOR',
        policy: { requiresSession: true },
    },
    {
        id: 'memory-pulse',
        title: 'Memory Pulse',
        description: 'Short-term, episodic, preference, and decay indicators.',
        slot: 'tertiary',
        category: 'AI_CONTROL',
        policy: { requiresSession: true, minTier: 'tablet' },
    },
    {
        id: 'permissions',
        title: 'Permission Decisions',
        description: 'Approval lattice for sensitive actions.',
        slot: 'tertiary',
        category: 'AI_CONTROL',
        policy: { requiresSession: true },
        tone: 'warning',
    },
    {
        id: 'config-matrix',
        title: 'Configuration Matrix',
        description: 'Policy-driven control matrix for OpenClaw + NeuroRift.',
        slot: 'dock',
        category: 'SYSTEM',
        policy: { controlOnly: false },
    },
    {
        id: 'online-mode',
        title: 'Online Mode',
        description: 'Secure tunnel exposure with explicit access control.',
        slot: 'dock',
        category: 'AI_CONTROL',
        policy: { controlOnly: false },
    },
    {
        id: 'manual-tool',
        title: 'Manual Operator Plane',
        description: 'Direct tool execution surface (No AI).',
        slot: 'secondary',
        category: 'OPERATOR',
        policy: { controlOnly: true, requiresSession: true },
        tone: 'warning',
    },
    {
        id: 'session-manager',
        title: 'Session Manager',
        description: 'Lifecycle control for active/archived sessions.',
        slot: 'dock',
        category: 'OPERATOR',
        policy: { controlOnly: false },
        tone: 'neutral',
    },
    {
        id: 'artifact-viewer',
        title: 'Artifact Inspector',
        description: 'Raw output and evidence explorer.',
        slot: 'tertiary',
        category: 'OPERATOR',
        policy: { requiresSession: true },
        tone: 'neutral',
    },
    {
        id: 'system-health',
        title: 'System Health',
        description: 'Real-time system resource monitoring',
        slot: 'dock',
        category: 'SYSTEM',
        policy: {
            minTier: 'tablet',
            mode: 'read',
        },
    },
];

export const layoutZones: Record<PanelSlot, PanelId[]> = {
    primary: ['command', 'agent-graph', 'intent-flow'],
    secondary: ['activity', 'manual-tool', 'execution-timeline'],
    tertiary: ['memory-pulse', 'permissions', 'artifact-viewer'],
    dock: ['session-manager', 'config-matrix', 'online-mode', 'system-health'],
};
